In [2]:
import torch
import numpy as np 

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


#### $ Simple \ Neural \ Network $

In [3]:
# Create a Tensorflow
a = torch.FloatTensor(2,3)
a

tensor([[0.0000e+00, 6.8664e-44, 7.0295e+28],
        [6.1949e-04, 1.9070e-19, 7.5553e+28]])

In [4]:
# Pass or transform into 0
a.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# creating a Tensors full of zeros
n = np.zeros(shape=(3,2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

#### $ Scalar \ Tensors  $

In [11]:
a = torch.Tensor([1,2,3])
a

tensor([1., 2., 3.])

In [13]:
s = a.sum()
s

tensor(6.)

#### $ NN building \ blocks  $



In [10]:
import torch.nn as nn 

layer = nn.Linear(2,5)
vector = torch.FloatTensor([1,2])
print(layer)
print(vector)


# Multiplying Both 
simple_layer = layer(vector)
simple_layer

Linear(in_features=2, out_features=5, bias=True)
tensor([1., 2.])


tensor([-1.3169, -0.3719, -0.3944, -1.1312,  1.1034], grad_fn=<AddBackward0>)

In [13]:
# Creating Sequences model 
mylayersequences = nn.Sequential(
    nn.Linear(in_features=2, out_features=5),
    nn.ReLU(),
    nn.Linear(in_features=5, out_features=20),
    nn.ReLU(),
    nn.Linear(in_features=20, out_features=10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1)
)

mylayersequences

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3, inplace=False)
  (6): Softmax(dim=1)
)

In [17]:
mylayersequences(torch.FloatTensor([[1,2]]))

tensor([[0.0987, 0.1049, 0.1153, 0.0734, 0.0704, 0.1172, 0.1342, 0.0934, 0.1180,
         0.0746]], grad_fn=<SoftmaxBackward0>)